/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leap.year;

/**
 *
 * @author hp
 */
public class NewApplet extends java.applet.Applet {

    /**
     * Initializes the applet NewApplet
     */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        button1 = new java.awt.Button();
        a = new java.awt.TextField();
        b = new java.awt.TextField();

        setLayout(null);

        label1.setText("Enter number");
        add(label1);
        label1.setBounds(80, 50, 100, 30);

        button1.setLabel("check");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(150, 120, 60, 24);
        add(a);
        a.setBounds(200, 50, 140, 30);
        add(b);
        b.setBounds(40, 190, 300, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
    int year=Integer.parseInt(a.getText());
    if (year%4==0)
    {
        b.setText(a.getText()+"year is leap");
    }
    else
    {
        b.setText(a.getText()+"year is not leap");    
    }
  
    
              
              
              
              
    }//GEN-LAST:event_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField a;
    private java.awt.TextField b;
    private java.awt.Button button1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
