/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
/**
 *
 * @author hp
 */
public class f3 extends javax.swing.JFrame {

    /**
     * Creates new form f3
     */
    public f3() {
        initComponents();
         this.setLocationRelativeTo(null);
        loadrecord(JTable1);
        id.setText("0");
         a.setText("");
         b.setText("");
         save.setEnabled(true);
         update1.setEnabled(true);
         delete.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        JTable1 = new javax.swing.JTable();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        JTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JTable1);
        if (JTable1.getColumnModel().getColumnCount() > 0) {
            JTable1.getColumnModel().getColumn(0).setResizable(false);
            JTable1.getColumnModel().getColumn(1).setResizable(false);
            JTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(260, 80, 360, 210);

        a.setBackground(new java.awt.Color(240, 240, 240));
        a.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        a.setForeground(new java.awt.Color(240, 240, 240));
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(30, 90, 213, 38);

        b.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(30, 169, 213, 40);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Product Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 60, 100, 27);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Price :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 135, 67, 27);

        delete.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(30, 273, 90, 40);

        save.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(30, 227, 89, 39);

        clear.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(146, 272, 90, 42);

        jButton1.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 20, 70, 27);

        update1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        update1.setText("Update");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        getContentPane().add(update1);
        update1.setBounds(146, 227, 90, 39);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("ID :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(31, 32, 25, 26);

        id.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        id.setForeground(new java.awt.Color(240, 240, 240));
        id.setText("0");
        getContentPane().add(id);
        id.setBounds(64, 32, 60, 26);

        exit.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(550, 20, 55, 27);

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\333.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -10, 630, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void loadrecord(JTable table)
    {
     try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://Localhost:3306/orderingsystem","root","");
            String sql= "select * from tbl2";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
           DefaultTableModel model =(DefaultTableModel)table.getModel();
           model.setRowCount(0);
           Object[] row;
           while (rs.next())
           {
           row= new Object[3];
           row[0]=rs.getInt(1);
            row[1]=rs.getString(2);
             row[2]=rs.getInt(3);
             model.addRow(row);
           }
           con.close();

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    
    }
    private void JTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable1MouseClicked
        save.setEnabled(false);
        update1.setEnabled(true);
        delete.setEnabled(true);
        int rowIndex= JTable1.getSelectedRow();
        id.setText(JTable1.getValueAt(rowIndex,0).toString());
        a.setText(JTable1.getValueAt(rowIndex,1).toString());
        b.setText(JTable1.getValueAt(rowIndex,2).toString());
    }//GEN-LAST:event_JTable1MouseClicked

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://Localhost:3306/orderingsystem","root","");
            String ID = id.getText();
            if(ID.equals("0"))
            {
                JOptionPane.showMessageDialog(null,"NO DATA SELECTED!");
            }
            else
            {
                String sql= "delete from tbl2 where id like '"+ID+"'";
                PreparedStatement pst=con.prepareStatement(sql);
                pst.execute();
                con.close();
                JOptionPane.showMessageDialog(null,"Delete Succesfully");
                loadrecord(JTable1);
                id.setText("0");
                a.setText("");
                b.setText("");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_deleteActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String product = a.getText();
        String price = b.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://Localhost:3306/orderingsystem","root","");
            String sql= "insert into tbl2 (products , price) values (?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,product);
            pst.setString(2,price);
            pst.execute();
            loadrecord(JTable1);
            con.close();
            JOptionPane.showMessageDialog(null,"Save Succesfully");

            id.setText("0");
            a.setText("");
            b.setText("");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        id.setText("0");
        a.setText("");
        b.setText("");
        save.setEnabled(true);
        update1.setEnabled(true);
        delete.setEnabled(true);

    }//GEN-LAST:event_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new f4().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        String ID = id.getText();
        String product = a.getText();
        String price = b.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://Localhost:3306/orderingsystem","root","");
            String sql= "update tbl2 set products ='"+product+"' , price='"+price+"'where id like '"+ID+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.execute();
            con.close();
            JOptionPane.showMessageDialog(null,"UPDATED Sucessfully");
            loadrecord(JTable1);
            id.setText("0");
            a.setText("");
            b.setText("");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_update1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
   System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable1;
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton save;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
